/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import axios from './axios.instance';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';

import type {
  Feedback
} from './model';

/**
 * @summary Submit Feedback
 */
export const submitFeedbackSubmitFeedbackPost = <TData = AxiosResponse<unknown>>(
  feedback: Feedback, options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.post(
    `/submit-feedback`,
    feedback, options
  );
}

/**
 * @summary Get Submissions
 */
export const getSubmissionsSubmissionsGet = <TData = AxiosResponse<Feedback[]>>(
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get(
    `/submissions`, options
  );
}

export type SubmitFeedbackSubmitFeedbackPostResult = AxiosResponse<unknown>
export type GetSubmissionsSubmissionsGetResult = AxiosResponse<Feedback[]>
