/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface Feedback {
  /** @minLength 1 */
  name: string;
  email: string;
  /** @minLength 5 */
  message: string;
  submitted_at?: string;
}
